# Development specific configuration
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        
logging:
  level:
    com.namhatta: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    org.springframework.security: DEBUG
    
# Enable detailed error responses in development
server:
  error:
    include-stacktrace: always
    include-exception: true