spring:
  profiles:
    active: production
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      password: ${REDIS_PASSWORD:}

# Application Configuration
app:
  auth:
    enabled: true
    bypass-allowed: false
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://*.replit.app}
  security:
    headers-enabled: true
  rate-limit:
    enabled: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# Logging Configuration
logging:
  level:
    com.namhatta: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/namhatta-app.log
    max-size: 100MB
    max-history: 30

# Management endpoints (restricted in production)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized